import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { mapTokens, readRow } from '../src/mapping.js';
import { renderCellsTable, renderRowResult } from '../src/ocr-view.js';
const fixture = JSON.parse(readFileSync(join(process.cwd(), 'tests/fixtures/mock_page_tokens.json'), 'utf8'));
const mapped = mapTokens(fixture.tokens);
let failures = 0; let pass = 0;
const check = (name, ok) => { if (ok) pass += 1; else { failures += 1; console.log('FAIL  ' + name); } };
const table = renderCellsTable(mapped);
check('table lists a clean value', table.includes('<td>3.5</td>'));
check('table marks a guess with a warning', table.includes('\u26a0') && table.includes('space inside the number'));
check('table lists unreadable ink', table.includes('ink found, could not read'));
check('table shows no printed Ideal value as handwriting (3.3 is boys month 0 ideal)', !table.includes('<td>3.3</td>'));
check('table refuses a bad page with a reason', renderCellsTable({ ok: false, problems: ['no headers'] }).includes('no headers'));
const row = renderRowResult(readRow(mapped, { month: 0, sex: 'P' }));
check('row result shows the weight', row.includes('2.8'));
check('row result warns about the length', row.includes('space inside the number'));
const xss = renderRowResult({ sex: 'L', month: 1, weight: { value: null, status: 'unreadable', cell: { text: '<b>x</b>' } }, length: { value: 1, status: 'ok', cell: null }, flags: ['<script>1</script>'] });
check('text from the photo is escaped, never run as code', !xss.includes('<script>') && !xss.includes('<b>x</b>'));
console.log(`OCR view: ${pass} passed${failures ? `, ${failures} FAILED` : ''}`);
process.exit(failures ? 1 : 0);
