import { bmi, checkVitals } from '../src/vitals.js';
let failures = 0; let pass = 0;
const check = (name, ok, detail = '') => { if (ok) pass += 1; else { failures += 1; console.log(`FAIL  ${name} ${detail}`); } };
check('BMI 62.4 kg, 165 cm = 22.9', bmi(62.4, 165) === 22.9);
check('BMI 85.5 kg, 168 cm = 30.3', bmi(85.5, 168) === 30.3);
check('BMI needs both numbers', bmi(70, null) === null && bmi(null, 170) === null && bmi(70, 0) === null);
let r = checkVitals({ sys: 120, dia: 80, pulse: 72, temp: 36.5, weight: 62.4, height: 165 });
check('a complete, consistent sheet has no flags and a BMI', r.flags.length === 0 && r.bmi === 22.9 && r.missing.length === 0, JSON.stringify(r));
r = checkVitals({ sys: 81, dia: 86, pulse: 78, temp: 36.7, weight: 66, height: 158 });
check('systolic below diastolic is flagged (catches a lost first digit: 138 read as 81)', r.flags.length === 1 && /Sistolik harus lebih besar/.test(r.flags[0]), JSON.stringify(r.flags));
r = checkVitals({ sys: 120, dia: 120, pulse: 70, temp: 36, weight: 60, height: 160 });
check('systolic equal to diastolic is flagged too', r.flags.length === 1);
r = checkVitals({ sys: null, dia: null, pulse: 70, temp: 36, weight: 60, height: 160 });
check('no blood pressure at all: reported as not recorded', r.flags.length === 1 && /belum dicatat/.test(r.flags[0]) && r.missing.includes('sys'));
r = checkVitals({ sys: 120, dia: null, pulse: 70, temp: 36, weight: 60, height: 160 });
check('only one of the two blood pressure numbers: reported as incomplete', r.flags.length === 1 && /belum lengkap/.test(r.flags[0]));
r = checkVitals({ sys: 120, dia: 80, pulse: null, temp: null, weight: null, height: null });
check('missing weight and height give two flags and no BMI', r.flags.length === 2 && r.bmi === null);
check('no clinical thresholds are used: 250/150 has no flag from this file', checkVitals({ sys: 250, dia: 150, pulse: 70, temp: 36, weight: 60, height: 160 }).flags.length === 0);
console.log(`Vitals: ${pass} passed${failures ? `, ${failures} FAILED` : ''}`);
process.exit(failures ? 1 : 0);
